name: world_on_rails
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - cudatoolkit>=10.1
  - pip>=21.0
  - python=3.7.9
  - pytorch>=1.4.0
  - pip:
      - pygame
      - dictor
      - lmdb
      - tqdm
      - matplotlib
      - moviepy
      - imageio
      - imageio-ffmpeg
      - imgaug
      - requests
      - opencv-python
      - pyyaml
      - py_trees==0.8.3
      - ray==1.1.0
      - shapely
      - tabulate
      - six
      - wandb
      - xmlschema
      - numpy
      - scipy==1.1.0
      - gym
      - atari-py

#From visualize_atari
#      - numpy
#      - scipy==1.1.0
#      - matplotlib
#      - torch==0.3.1
#      - jupyter
#      - gym
#      - atari-py
#      sudo apt install ffmpeg